package mnm.hibernate;

// default package
// Generated Apr 11, 2010 12:10:19 AM by Hibernate Tools 3.2.2.GA

/**
 * Class generated by hbm2java
 */
public class Class implements java.io.Serializable {

	private Byte id;
	private String name;
	private String reshte;
	private byte schoolid;
	private String kind;

	public Class() {
	}

	public Class(byte schoolid) {
		this.schoolid = schoolid;
	}

	public Class(String name, String reshte, byte schoolid, String kind) {
		this.name = name;
		this.reshte = reshte;
		this.schoolid = schoolid;
		this.kind = kind;
	}

	public Byte getId() {
		return this.id;
	}

	public void setId(Byte id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getReshte() {
		return this.reshte;
	}

	public void setReshte(String reshte) {
		this.reshte = reshte;
	}

	public byte getSchoolid() {
		return this.schoolid;
	}

	public void setSchoolid(byte schoolid) {
		this.schoolid = schoolid;
	}

	public String getKind() {
		return this.kind;
	}

	public void setKind(String kind) {
		this.kind = kind;
	}

}
