package mnm.hibernate;
// default package
// Generated Apr 11, 2010 12:10:19 AM by Hibernate Tools 3.2.2.GA

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	private CourseId id;

	public Course() {
	}

	public Course(CourseId id) {
		this.id = id;
	}

	public CourseId getId() {
		return this.id;
	}

	public void setId(CourseId id) {
		this.id = id;
	}

}
