package mnm.hibernate;
// default package
// Generated Apr 11, 2010 12:10:19 AM by Hibernate Tools 3.2.2.GA

/**
 * Dars generated by hbm2java
 */
public class Dars implements java.io.Serializable {

	private Integer mainid;
	private byte id;
	private String name;
	private String code;
	private Double vahed;

	public Dars() {
	}

	public Dars(byte id, String name) {
		this.id = id;
		this.name = name;
	}

	public Dars(byte id, String name, String code, Double vahed) {
		this.id = id;
		this.name = name;
		this.code = code;
		this.vahed = vahed;
	}

	public Integer getMainid() {
		return this.mainid;
	}

	public void setMainid(Integer mainid) {
		this.mainid = mainid;
	}

	public byte getId() {
		return this.id;
	}

	public void setId(byte id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Double getVahed() {
		return this.vahed;
	}

	public void setVahed(Double vahed) {
		this.vahed = vahed;
	}

}
