package mnm.hibernate;
// default package
// Generated Apr 11, 2010 12:10:19 AM by Hibernate Tools 3.2.2.GA

/**
 * Kind generated by hbm2java
 */
public class Kind implements java.io.Serializable {

	private Integer id;
	private String name;
	private int scholid;

	public Kind() {
	}

	public Kind(String name, int scholid) {
		this.name = name;
		this.scholid = scholid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getScholid() {
		return this.scholid;
	}

	public void setScholid(int scholid) {
		this.scholid = scholid;
	}

}
