package mnm.hibernate;
// default package
// Generated Apr 11, 2010 12:10:19 AM by Hibernate Tools 3.2.2.GA

/**
 * ListId generated by hbm2java
 */
public class ListId implements java.io.Serializable {

	private Integer key;
	private int id;
	private int listId;

	public ListId() {
	}

	public ListId(int id, int listId) {
		this.id = id;
		this.listId = listId;
	}

	public Integer getKey() {
		return this.key;
	}

	public void setKey(Integer key) {
		this.key = key;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getListId() {
		return this.listId;
	}

	public void setListId(int listId) {
		this.listId = listId;
	}

}
