package mnm.hibernate;
// default package
// Generated Apr 11, 2010 12:10:19 AM by Hibernate Tools 3.2.2.GA

/**
 * Prof generated by hbm2java
 */
public class Prof implements java.io.Serializable {

	private ProfId id;

	public Prof() {
	}

	public Prof(ProfId id) {
		this.id = id;
	}

	public ProfId getId() {
		return this.id;
	}

	public void setId(ProfId id) {
		this.id = id;
	}

}
