package mnm.hibernate;
// default package
// Generated Apr 11, 2010 12:10:19 AM by Hibernate Tools 3.2.2.GA

/**
 * Reshte generated by hbm2java
 */
public class Reshte implements java.io.Serializable {

	private Byte id;
	private String name;
	private int maghta;

	public Reshte() {
	}

	public Reshte(String name, int maghta) {
		this.name = name;
		this.maghta = maghta;
	}

	public Byte getId() {
		return this.id;
	}

	public void setId(Byte id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getMaghta() {
		return this.maghta;
	}

	public void setMaghta(int maghta) {
		this.maghta = maghta;
	}

}
