package mnm.hibernate;
// default package
// Generated Apr 11, 2010 12:10:19 AM by Hibernate Tools 3.2.2.GA

/**
 * RoomWeekBusy generated by hbm2java
 */
public class RoomWeekBusy implements java.io.Serializable {

	private Integer key;
	private int id;
	private String dayBusy;
	private String prof;
	private String course;
	private int seatnum;
	private int day;
	private int hour;

	public RoomWeekBusy() {
	}

	public RoomWeekBusy(int id, String prof, String course, int seatnum,
			int day, int hour) {
		this.id = id;
		this.prof = prof;
		this.course = course;
		this.seatnum = seatnum;
		this.day = day;
		this.hour = hour;
	}

	public RoomWeekBusy(int id, String dayBusy, String prof, String course,
			int seatnum, int day, int hour) {
		this.id = id;
		this.dayBusy = dayBusy;
		this.prof = prof;
		this.course = course;
		this.seatnum = seatnum;
		this.day = day;
		this.hour = hour;
	}

	public Integer getKey() {
		return this.key;
	}

	public void setKey(Integer key) {
		this.key = key;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDayBusy() {
		return this.dayBusy;
	}

	public void setDayBusy(String dayBusy) {
		this.dayBusy = dayBusy;
	}

	public String getProf() {
		return this.prof;
	}

	public void setProf(String prof) {
		this.prof = prof;
	}

	public String getCourse() {
		return this.course;
	}

	public void setCourse(String course) {
		this.course = course;
	}

	public int getSeatnum() {
		return this.seatnum;
	}

	public void setSeatnum(int seatnum) {
		this.seatnum = seatnum;
	}

	public int getDay() {
		return this.day;
	}

	public void setDay(int day) {
		this.day = day;
	}

	public int getHour() {
		return this.hour;
	}

	public void setHour(int hour) {
		this.hour = hour;
	}

}
