package mnm.hibernate;
// default package
// Generated Apr 11, 2010 12:10:19 AM by Hibernate Tools 3.2.2.GA

/**
 * Scholl generated by hbm2java
 */
public class Scholl implements java.io.Serializable {

	private Integer id;
	private String name;
	private String shomare;
	private int mantaghe;
	private String ostan;
	private int num;
	private int classnum;
	private String value;
	private boolean dolati;

	public Scholl() {
	}

	public Scholl(String name, String shomare, int mantaghe, String ostan,
			int num, int classnum, String value, boolean dolati) {
		this.name = name;
		this.shomare = shomare;
		this.mantaghe = mantaghe;
		this.ostan = ostan;
		this.num = num;
		this.classnum = classnum;
		this.value = value;
		this.dolati = dolati;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getShomare() {
		return this.shomare;
	}

	public void setShomare(String shomare) {
		this.shomare = shomare;
	}

	public int getMantaghe() {
		return this.mantaghe;
	}

	public void setMantaghe(int mantaghe) {
		this.mantaghe = mantaghe;
	}

	public String getOstan() {
		return this.ostan;
	}

	public void setOstan(String ostan) {
		this.ostan = ostan;
	}

	public int getNum() {
		return this.num;
	}

	public void setNum(int num) {
		this.num = num;
	}

	public int getClassnum() {
		return this.classnum;
	}

	public void setClassnum(int classnum) {
		this.classnum = classnum;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public boolean isDolati() {
		return this.dolati;
	}

	public void setDolati(boolean dolati) {
		this.dolati = dolati;
	}

}
