package mnm.hibernate;
// default package
// Generated Apr 11, 2010 12:10:19 AM by Hibernate Tools 3.2.2.GA

/**
 * Schollday generated by hbm2java
 */
public class Schollday implements java.io.Serializable {

	private Integer id;
	private Integer scholid;
	private String day;
	private int count;

	public Schollday() {
	}

	public Schollday(String day, int count) {
		this.day = day;
		this.count = count;
	}

	public Schollday(Integer scholid, String day, int count) {
		this.scholid = scholid;
		this.day = day;
		this.count = count;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getScholid() {
		return this.scholid;
	}

	public void setScholid(Integer scholid) {
		this.scholid = scholid;
	}

	public String getDay() {
		return this.day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	public int getCount() {
		return this.count;
	}

	public void setCount(int count) {
		this.count = count;
	}

}
