package mnm.hibernate;
// default package
// Generated Apr 11, 2010 12:10:19 AM by Hibernate Tools 3.2.2.GA

/**
 * SoustuId generated by hbm2java
 */
public class SoustuId implements java.io.Serializable {

	private int id;
	private String profName;
	private String courseName;
	private int dur;
	private int listnum;
	private String name;

	public SoustuId() {
	}

	public SoustuId(int id, String profName, String courseName, int dur,
			int listnum, String name) {
		this.id = id;
		this.profName = profName;
		this.courseName = courseName;
		this.dur = dur;
		this.listnum = listnum;
		this.name = name;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getProfName() {
		return this.profName;
	}

	public void setProfName(String profName) {
		this.profName = profName;
	}

	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	public int getDur() {
		return this.dur;
	}

	public void setDur(int dur) {
		this.dur = dur;
	}

	public int getListnum() {
		return this.listnum;
	}

	public void setListnum(int listnum) {
		this.listnum = listnum;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SoustuId))
			return false;
		SoustuId castOther = (SoustuId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getProfName() == castOther.getProfName()) || (this
						.getProfName() != null
						&& castOther.getProfName() != null && this
						.getProfName().equals(castOther.getProfName())))
				&& ((this.getCourseName() == castOther.getCourseName()) || (this
						.getCourseName() != null
						&& castOther.getCourseName() != null && this
						.getCourseName().equals(castOther.getCourseName())))
				&& (this.getDur() == castOther.getDur())
				&& (this.getListnum() == castOther.getListnum())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result
				+ (getProfName() == null ? 0 : this.getProfName().hashCode());
		result = 37
				* result
				+ (getCourseName() == null ? 0 : this.getCourseName()
						.hashCode());
		result = 37 * result + this.getDur();
		result = 37 * result + this.getListnum();
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

}
