package mnm.hibernate;
// default package
// Generated Apr 11, 2010 12:10:19 AM by Hibernate Tools 3.2.2.GA

/**
 * Soustu generated by hbm2java
 */
public class Soustu implements java.io.Serializable {

	private SoustuId id;

	public Soustu() {
	}

	public Soustu(SoustuId id) {
		this.id = id;
	}

	public SoustuId getId() {
		return this.id;
	}

	public void setId(SoustuId id) {
		this.id = id;
	}

}
