package mnm.hibernate;
// default package
// Generated Apr 11, 2010 12:10:19 AM by Hibernate Tools 3.2.2.GA

/**
 * Stu generated by hbm2java
 */
public class Stu implements java.io.Serializable {

	private StuId id;

	public Stu() {
	}

	public Stu(StuId id) {
		this.id = id;
	}

	public StuId getId() {
		return this.id;
	}

	public void setId(StuId id) {
		this.id = id;
	}

}
